# Generated by Django 5.0.6 on 2024-07-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_is_bankrupt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_bankrupt',
            field=models.BooleanField(default=False),
        ),
    ]
